<?php declare(strict_types = 1);

namespace Luky\Console;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DummyCommand extends Command
{
	protected function configure()
	{
		parent::configure(); // TODO: Change the autogenerated stub
		
		$this->setName('dummy');
	}
	
	protected function execute(InputInterface $input, OutputInterface $output)
	{
		$output->writeln(\get_class($output));
		
		
		$output->writeln('Some fancy text');
		
		$progressBar = new FancyProgressBar($output);
		$progressBar->setMaxSteps(3000);
		
		for ($i = 0; $i <= 3000; $i++) {
			
			for ($j = 0; $j <= 3000; $j++) {
				// slow lil bit
				continue;
			}
			
			$progressBar->advance();
		}
		
		$output->writeln('Done');
		
	}
}
